### PR TITLE
#1021 Pin mcp >=1.23.0,<2.0 and tighten langchain-mcp-adapters ceiling to <0.2.0

### LINKED ISSUE #1021: ImportError: cannot import name 'AudioContent' from 'mcp.types' when starting Neuro-san
I experienced this on a fresh checkout of `neuro-san-studio` but @Noravee asked me to open a ticket here.

After cloning the repo, setting up a venv, and installing `requirements.txt` and `requirements-build.txt`, on starting the server I get the following errors. Both the http service and NSFlow service aren't running, despite the "success" message, as verified by testing and `netstat`.

```console
When running this Python app I get the error below. I've installed requirements.txt and requirements.build.txt in my venv.  

INFO     nsflow - INFO:     Will watch for changes in these directories: ['/home/darren/src/cognizant/platform/neuro-san-studio']                                
INFO     nsflow - INFO:     Uvicorn running on http://localhost:4173 (Press CTRL+C to quit)                                                                      
INFO     nsflow - INFO:     Started reloader process [82178] using StatReload                                                                                    
ERROR    NeuroSan - Traceback (most recent call last):                                                                                                           
INFO     NeuroSan -   File "<frozen runpy>", line 198, in _run_module_as_main                                                                                    
INFO     NeuroSan -   File "<frozen runpy>", line 88, in _run_code                                                                                               
INFO     NeuroSan -   File "/home/darren/src/cognizant/platform/neuro-san-studio/neuro_san_studio/runner/neuro_san_server_wrapper.py", line 28, in <module>      
INFO     NeuroSan -     from neuro_san.service.main_loop.server_main_loop import ServerMainLoop                                                                  
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/service/main_loop/server_main_loop.py", line 40, in        
         <module>                                                                                                                                                
INFO     NeuroSan -     from neuro_san.service.http.server.http_server import DEFAULT_SERVER_NAME                                                                
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/service/http/server/http_server.py", line 38, in <module>  
INFO     NeuroSan -     from neuro_san.service.generic.async_agent_service_provider import AsyncAgentServiceProvider                                             
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/service/generic/async_agent_service_provider.py", line     
         27, in <module>                                                                                                                                         
INFO     NeuroSan -     from neuro_san.service.generic.async_agent_service import AsyncAgentService                                                              
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/service/generic/async_agent_service.py", line 50, in       
         <module>                                                                                                                                                
INFO     NeuroSan -     from neuro_san.session.async_direct_agent_session import AsyncDirectAgentSession                                                         
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/session/async_direct_agent_session.py", line 33, in        
         <module>                                                                                                                                                
INFO     NeuroSan -     from neuro_san.internals.chat.data_driven_chat_session import DataDrivenChatSession                                                      
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/chat/data_driven_chat_session.py", line 40, in   
         <module>                                                                                                                                                
INFO     NeuroSan -     from neuro_san.internals.graph.registry.agent_tool_registry import AgentToolRegistry                                                     
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/registry/agent_tool_registry.py", line     
         22, in <module>                                                                                                                                         
INFO     NeuroSan -     from neuro_san.internals.graph.registry.activation_factory import ActivationFactory                                                      
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/registry/activation_factory.py", line 28,  
         in <module>                                                                                                                                             
INFO     NeuroSan -     from neuro_san.internals.graph.activations.branch_activation import BranchActivation                                                     
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/activations/branch_activation.py", line    
         30, in <module>                                                                                                                                         
INFO     NeuroSan -     from neuro_san.internals.graph.activations.calling_activation import CallingActivation                                                   
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/activations/calling_activation.py", line   
         29, in <module>                                                                                                                                         
INFO     NeuroSan -     from neuro_san.internals.run_context.factory.run_context_factory import RunContextFactory                                                
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/factory/run_context_factory.py",     
         line 25, in <module>                                                                                                                                    
INFO     NeuroSan -     from neuro_san.internals.run_context.langchain.core.langchain_run_context import LangChainRunContext                                     
INFO     NeuroSan -   File                                                                                                                                       
         "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/langchain/core/langchain_run_context.py", line 55, in  
         <module>                                                                                                                                                
INFO     NeuroSan -     from neuro_san.internals.run_context.langchain.core.base_tool_factory import BaseToolFactory                                             
INFO     NeuroSan -   File                                                                                                                                       
         "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/langchain/core/base_tool_factory.py", line 37, in      
         <module>                                                                                                                                                
INFO     NeuroSan -     from neuro_san.internals.run_context.langchain.mcp.langchain_mcp_adapter import LangChainMcpAdapter                                      
INFO     NeuroSan -   File                                                                                                                                       
         "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/langchain/mcp/langchain_mcp_adapter.py", line 29, in   
         <module>                                                                                                                                                
INFO     NeuroSan -     from langchain_mcp_adapters.client import MultiServerMCPClient                                                                           
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/langchain_mcp_adapters/client.py", line 31, in <module>              
INFO     NeuroSan -     from langchain_mcp_adapters.tools import load_mcp_tools                                                                                  
INFO     NeuroSan -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/langchain_mcp_adapters/tools.py", line 21, in <module>               
INFO     NeuroSan -     from mcp.types import (                                                                                                                  
INFO     NeuroSan - ImportError: cannot import name 'AudioContent' from 'mcp.types'                                                                              
         (/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/mcp/types.py)                                                                          
INFO     nsflow - Process SpawnProcess-1:                                                                                                                        
ERROR    nsflow - Traceback (most recent call last):                                                                                                             
INFO     nsflow -   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap                                                               
INFO     nsflow -     self.run()                                                                                                                                 
INFO     nsflow -   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run                                                                      
INFO     nsflow -     self._target(*self._args, **self._kwargs)                                                                                                  
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started                
INFO     nsflow -     target(sockets=sockets)                                                                                                                    
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run                                    
INFO     nsflow -     return asyncio.run(self.serve(sockets=sockets))                                                                                            
INFO     nsflow -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            
INFO     nsflow -   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run                                                                              
INFO     nsflow -     return runner.run(main)                                                                                                                    
INFO     nsflow -            ^^^^^^^^^^^^^^^^                                                                                                                    
INFO     nsflow -   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run                                                                              
INFO     nsflow -     return self._loop.run_until_complete(task)                                                                                                 
INFO     nsflow -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                 
INFO     nsflow -   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete                                                           
INFO     nsflow -     return future.result()                                                                                                                     
INFO     nsflow -            ^^^^^^^^^^^^^^^                                                                                                                     
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve                                  
INFO     nsflow -     await self._serve(sockets)                                                                                                                 
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve                                 
INFO     nsflow -     config.load()                                                                                                                              
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load                                  
INFO     nsflow -     self.loaded_app = import_from_string(self.app)                                                                                             
INFO     nsflow -                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                             
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string                   
INFO     nsflow -     module = importlib.import_module(module_str)                                                                                               
INFO     nsflow -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                               
INFO     nsflow -   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module                                                                  
INFO     nsflow -     return _bootstrap._gcd_import(name[level:], package, level)                                                                                
INFO     nsflow -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                
INFO     nsflow -   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                                                                              
INFO     nsflow -   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                                                                           
INFO     nsflow -   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked                                                                  
INFO     nsflow -   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked                                                                            
INFO     nsflow -   File "<frozen importlib._bootstrap_external>", line 995, in exec_module                                                                      
INFO     nsflow -   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed                                                                 
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/nsflow/backend/main.py", line 26, in <module>                          
INFO     nsflow -     from nsflow.backend.api.router import router                                                                                               
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/nsflow/backend/api/router.py", line 20, in <module>                    
INFO     nsflow -     from .v1 import (                                                                                                                          
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/nsflow/backend/api/v1/agent_flows.py", line 27, in <module>            
INFO     nsflow -     from nsflow.backend.utils.agentutils.ns_websocket_utils import NsWebsocketUtils                                                            
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/nsflow/backend/utils/agentutils/ns_websocket_utils.py", line 26, in    
         <module>                                                                                                                                                
INFO     nsflow -     from neuro_san.client.agent_session_factory import AgentSessionFactory                                                                     
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/client/agent_session_factory.py", line 22, in <module>       
INFO     nsflow -     from neuro_san.client.direct_agent_session_factory import DirectAgentSessionFactory                                                        
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/client/direct_agent_session_factory.py", line 37, in         
         <module>                                                                                                                                                
INFO     nsflow -     from neuro_san.session.direct_agent_session import DirectAgentSession                                                                      
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/session/direct_agent_session.py", line 34, in <module>       
INFO     nsflow -     from neuro_san.internals.chat.data_driven_chat_session import DataDrivenChatSession                                                        
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/chat/data_driven_chat_session.py", line 40, in     
         <module>                                                                                                                                                
INFO     nsflow -     from neuro_san.internals.graph.registry.agent_tool_registry import AgentToolRegistry                                                       
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/registry/agent_tool_registry.py", line 22,   
         in <module>                                                                                                                                             
INFO     nsflow -     from neuro_san.internals.graph.registry.activation_factory import ActivationFactory                                                        
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/registry/activation_factory.py", line 28,    
         in <module>                                                                                                                                             
INFO     nsflow -     from neuro_san.internals.graph.activations.branch_activation import BranchActivation                                                       
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/activations/branch_activation.py", line 30,  
         in <module>                                                                                                                                             
INFO     nsflow -     from neuro_san.internals.graph.activations.calling_activation import CallingActivation                                                     
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/graph/activations/calling_activation.py", line     
         29, in <module>                                                                                                                                         
INFO     nsflow -     from neuro_san.internals.run_context.factory.run_context_factory import RunContextFactory                                                  
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/factory/run_context_factory.py", line  
         25, in <module>                                                                                                                                         
INFO     nsflow -     from neuro_san.internals.run_context.langchain.core.langchain_run_context import LangChainRunContext                                       
INFO     nsflow -   File                                                                                                                                         
         "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/langchain/core/langchain_run_context.py", line 55, in  
         <module>                                                                                                                                                
INFO     nsflow -     from neuro_san.internals.run_context.langchain.core.base_tool_factory import BaseToolFactory                                               
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/langchain/core/base_tool_factory.py",  
         line 37, in <module>                                                                                                                                    
INFO     nsflow -     from neuro_san.internals.run_context.langchain.mcp.langchain_mcp_adapter import LangChainMcpAdapter                                        
INFO     nsflow -   File                                                                                                                                         
         "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/neuro_san/internals/run_context/langchain/mcp/langchain_mcp_adapter.py", line 29, in   
         <module>                                                                                                                                                
INFO     nsflow -     from langchain_mcp_adapters.client import MultiServerMCPClient                                                                             
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/langchain_mcp_adapters/client.py", line 31, in <module>                
INFO     nsflow -     from langchain_mcp_adapters.tools import load_mcp_tools                                                                                    
INFO     nsflow -   File "/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/langchain_mcp_adapters/tools.py", line 21, in <module>                 
INFO     nsflow -     from mcp.types import (                                                                                                                    
INFO     nsflow - ImportError: cannot import name 'AudioContent' from 'mcp.types'                                                                                
         (/home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/mcp/types.py)
```

```console
lsb_release -a                                                                                                                       
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.4 LTS
Release:	24.04
Codename:	noble
```

```console
❯ python --version
Python 3.12.3

❯ pip --version
pip 24.0 from /home/darren/venv/neuro-san-studio/lib/python3.12/site-packages/pip (python 3.12)

❯ which python
/home/darren/venv/neuro-san-studio/bin/python
```

At Copilot's suggestion, I did this, which fixed it:

```console
python -m pip install --upgrade "mcp>=1.10"
```

Analysis by Copilot:

```console
requirements.txt likely allows ranges, so pip picked a combo that satisfies declared constraints but is runtime-incompatible at this import point."

In requirements.txt, these lines are the key:
neuro-san==0.6.57
langchain-mcp-adapters>=0.1.7,<1.0
Because langchain-mcp-adapters is not pinned, pip selected 0.1.14 (latest in range), which then pulled mcp==1.9.3 (allowed by its own constraints). That combo is what broke at runtime (AudioContent import mismatch).
So the issue is dependency drift via broad ranges, not your install process.
What to change (recommended)
In requirements.txt, replace the loose adapter line with an exact version known to work with neuro-san==0.6.57 (you’ll want to confirm from your team or prior lockfile):
from: langchain-mcp-adapters>=0.1.7,<1.0
to: langchain-mcp-adapters==<known-good>
Optionally also add a direct mcp pin to prevent transitive drift:
mcp==<known-good> (edited)
```

### PR DESCRIPTION
**Pull request by Noravee**
- Add an explicit `mcp` pin (`>=1.23.0` for OAuth client_credentials, required by the MCP Authentication work in #683;` <2.0` to avoid the upcoming breaking 2.x release). Fix #1021

- Tighten `langchain-mcp-adapters` to `<0.2.0`. The `0.2.0` release ships `langchain-ai/langchain-mcp-adapters#379`, which changes `ToolMessage.content` from a concatenated text string to a list of LangChain content blocks. `JournalingCallbackHandler.on_tool_end` calls `str()` on `.content`, so the journal would log the raw list structure instead of the tool's text.

### CODE REVIEW

**Comment by dsargent** [comment]
> Copilot wasn't able to review any files in this pull request.

???

**Review by dsargent — APPROVED** [review]
lgtm but I shouldn't be final approver.

**Review by ofrancon — APPROVED** [review]
lgtm

**Review by andreidenissov-cog — APPROVED** [review]
Looks good, AFAICT.

**Review by d1donlydfink — APPROVED** [review]
