### PR TITLE
Make neuro-san formally require Python 3.12 or above

### LINKED ISSUE #1293: neuro-san: drop support for python <3.12
Versions below Python `3.12` are NOT supported anymore by `neuro-san`.
Instead of trying to keep it backward compatible, I suggest we drop support for Python versions older than Python 3.12.
 
Reason:
`neuro-san` `0.6.98` relies on `eager_task_factory` that was introduced in Python 3.12. See [the Eager Task Factory doc](https://docs.python.org/3/library/asyncio-task.html#eager-task-factory)

Trying to run Neuro SAN with Python 3.11 gives the following error:

```
> python -m neuro_san.client.agent_cli --agent hello_world

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/754337/workspace/my_project_3/.venv/lib/python3.11/site-packages/neuro_san/client/agent_cli.py", line 34, in <module>
    from neuro_san.client.agent_session_factory import AgentSessionFactory
  File "/Users/754337/workspace/my_project_3/.venv/lib/python3.11/site-packages/neuro_san/client/agent_session_factory.py", line 22, in <module>
    from neuro_san.client.direct_agent_session_factory import DirectAgentSessionFactory
  File "/Users/754337/workspace/my_project_3/.venv/lib/python3.11/site-packages/neuro_san/client/direct_agent_session_factory.py", line 21, in <module>
    from leaf_common.asyncio.asyncio_executor_pool import AsyncioExecutorPool
  File "/Users/754337/workspace/my_project_3/.venv/lib/python3.11/site-packages/leaf_common/asyncio/asyncio_executor_pool.py", line 42, in <module>
    from leaf_common.asyncio.asyncio_executor import AsyncioExecutor
  File "/Users/754337/workspace/my_project_3/.venv/lib/python3.11/site-packages/leaf_common/asyncio/asyncio_executor.py", line 42, in <module>
    from asyncio import eager_task_factory
ImportError: cannot import name 'eager_task_factory' from 'asyncio' (/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/__init__.py)
```

Steps to reproduce:
In a new folder:
```
uv python pin 3.11
uv venv
source .venv/bin/activate
# Check the python version
python --version
  Python 3.11.13

uv pip install neuro-san
uv pip show neuro-san
  Name: neuro-san
  Version: 0.6.98
  ...

# Run Neuro SAN
python -m neuro_san.client.agent_cli --agent hello_world
  (exception pasted above)
```

### PR DESCRIPTION
**Pull request by ofrancon**
Makes neuro-san formally require Python 3.12 or above.
The code itself doesn't work with Python 3.11 since version `0.6.84` and leaf-common `1.2.49`.

Fixes #1293

### CODE REVIEW

File: .github/workflows/publish.yml [hunk 1]
```diff
@@ -28,7 +28,7 @@ jobs:
         # 1.0.9
         uses: cognizant-ai-lab/build-common/actions/setup-python-env@b14b3de23cb9aca02b2165e57542335e0c8f5304
         with:
-          python-version: '3.10'
+          python-version: '3.12'
```
Comment (ofrancon) [inline .github/workflows/publish.yml:31]: Technically not necessary as publishing doesn't run the code, but less confusing.

File: pyproject.toml [hunk 2]
```diff
@@ -16,9 +16,12 @@ keywords = ["LLM", "langchain", "agent", "multi-agent"]
 # https://packaging.python.org/en/latest/guides/licensing-examples-and-user-scenarios/
 license = "Apache-2.0"
 license-files = ["LICENSE.txt"]
-requires-python = ">=3.10"
+requires-python = ">=3.12"
```
Comment (ofrancon) [inline pyproject.toml:19]: That's the real change. It will prevent pip from installing `neuro-san` on Python 3.11, which would break anyway at run time.

**Comment by ofrancon** [comment]
Testing with Python 3.13 and 3.14 will be done under #1303

File: requirements.txt [hunk 3]
```diff
@@ -6,7 +6,7 @@
 # requirements-build.txt
 
 # In-house dependencies
-leaf-common>=1.3.1
+leaf-common>=1.4.0
```
Comment (ofrancon) [inline requirements.txt:9]: `leaf-common` `1.4.0` also enforces the Python 3.12+ rule.

**Review by Noravee — APPROVED** [review]
LGTM.

FYI: I think the first broken release was 0.6.84.

**Comment by ofrancon** [comment]
> FYI: I think the first broken release was 0.6.84.

Correct - I've updated the PR description. Sorry for the confusion.
